// <auto-generated />
namespace Mvc_CommentingChat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddDateTime_PropertyTo_The_CommentAndReplay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDateTime_PropertyTo_The_CommentAndReplay));
        
        string IMigrationMetadata.Id
        {
            get { return "201901042006337_AddDateTime_PropertyTo_The_CommentAndReplay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
